language: node_js
node_js:
  - 'node'
  - '10'
  - '8.3.0'

env:
  - WEBPACK_VERSION=4 EXTRACT_PLUGIN_VERSION=next

install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_PLUGIN_VERSION || true

script:
  - npm test

after_script:
  - $(npm bin)/codecov
